project_name: telemetry-envoy
before:
  hooks:
  - go mod download
builds:
- binary: telemetry-envoy
  env:
  - CGO_ENABLED=0
  goos:
    - darwin
    - linux
    - windows
  ignore:
  - goos: darwin
    goarch: 386
archives:
  -
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
nfpms:
  -
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    vendor: Rackspace
    homepage: https://www.rackspace.com/
    description: Monitoring application which submits system metrics for further analysis.
    license: Apache 2.0
    maintainer: monitoring@rackspace.com
    formats:
      - deb
    scripts:
      postinstall: pkg/scripts/postinstall.sh
    files:
      pkg/files/rackspace-monitoring-envoy.service: /etc/systemd/system/rackspace-monitoring-envoy.service
      pkg/files/rackspace-monitoring-envoy-config.yaml: /etc/rackspace-monitoring-envoy-config.yaml      
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "SNAPSHOT-{{.ShortCommit}}"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^misc:'
    - '^test:'
    - '^build:'
release:
  github:
    owner: GeorgeJahad
    name: try-flyway