project_name: telemetry-envoy
before:
  hooks:
  - go mod download
builds:
- binary: telemetry-envoy
  env:
  - CGO_ENABLED=0
  goos:
    - darwin
    - linux
    - windows
  ignore:
  - goos: darwin
    goarch: 386
archives:
  -
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
nfpms:
  -
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    vendor: Rackspace
    homepage: https://www.rackspace.com/
    description: Monitoring application which submits system metrics for further analysis.
    license: Apache 2.0
    maintainer: monitoring@rackspace.com
    formats:
      - deb
      - rpm
    scripts:
      preinstall: pkg/scripts/preinstall.sh
      postinstall: pkg/scripts/postinstall.sh
      preremove: pkg/scripts/preremove.sh
      postremove: pkg/scripts/postremove.sh
    files:
      # Might need to stage these files and install them according to distro, such as
      # https://github.com/influxdata/telegraf/blob/bae12dde1e2df495e647459e2d882a1f0604331b/scripts/post-install.sh#L50
      pkg/files/telemetry-envoy.service: /usr/lib/telemetry-envoy/scripts/telemetry-envoy.service
      pkg/files/telemetry-envoy.preset: /usr/lib/telemetry-envoy/scripts/telemetry-envoy.preset
      pkg/files/telemetry-envoy.yaml: /etc/salus/telemetry-envoy.yaml
    empty_folders:
    - /var/lib/telemetry-envoy
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "SNAPSHOT-{{.ShortCommit}}"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^misc:'
    - '^test:'
    - '^build:'
release:
  github:
    owner: racker
    name: salus-telemetry-envoy
